name: getx_study
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.17.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rxdart: null
  get: null
  card_swiper: null
  webview_flutter: ^3.0.4
  pull_to_refresh: null
  flutter_slidable: null
  image_picker: null
  cached_network_image: null
  lpinyin: null
  shared_preferences: null
  path_provider: null
  event_bus: null
  dio: null
  url_launcher: null
  image_gallery_saver: null
  open_file: null
  pretty_dio_logger: null
  r_dart_library:
    git:
      url: 'https://github.com/YK-Unit/r_dart_library.git'
      ref: 0.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/ic_head.jpeg
  - assets/images/ic_eye.png
  - assets/images/placeholder.png
  - assets/images/saber.jpg
  - assets/images/season_ali_pay.jpg
  - assets/images/saber_logo.jpg
  - assets/images/welcome_1.png
  - assets/images/welcome_2.jpg
  - assets/images/launchImage.png
  - assets/images/upgrade.png
flr:
  core_version: 3.1.0
  dartfmt_line_length: 80
  assets: []
  fonts: []
