name: getx_study
description: A GetX Study Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.17.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  card_swiper: ^2.0.4
  webview_flutter: ^4.0.2
  pull_to_refresh: ^2.0.0
  flutter_slidable: ^2.0.0
  cached_network_image: ^3.2.1
  lpinyin: ^2.0.3
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  marquee: ^2.2.3
  flutter_easyloading: ^3.0.5
  share: ^2.0.4
  r_dart_library:
    git:
      url: 'https://github.com/YK-Unit/r_dart_library.git'
      ref: 0.4.1
  rxdart: ^0.27.5
  image_picker: ^0.8.5+3
  url_launcher: ^6.1.5
  image_gallery_saver: ^1.7.1
  path_provider: ^2.0.11
  event_bus: ^2.0.0
  open_file: ^3.2.1
  permission_handler: ^10.0.0
  logger: ^1.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/ic_eye.png
  - assets/images/ic_head.jpeg
  - assets/images/launchImage.png
  - assets/images/placeholder.png
  - assets/images/saber.jpg
  - assets/images/saber_logo.jpg
  - assets/images/season_ali_pay.jpg
  - assets/images/upgrade.png
  - assets/images/welcome_1.png
  - assets/images/welcome_2.jpg
  - assets/html/index.html
flr:
  core_version: 3.1.0
  dartfmt_line_length: 80
  assets: []
  fonts: []
